repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
    exclude: README.md

- repo: https://github.com/ambv/black
  rev: 23.12.0
  hooks:
  - id: black
    name: Blacken

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--count, --show-source, --statistics]
    additional_dependencies:
      - flake8-bugbear==22.7.1

