repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: trailing-whitespace
      exclude: README.md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
        - id: ruff
          args: [--fix]
        - id: ruff-format

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
        - id: nbqa-pyupgrade
          args: [--py39-plus]
        - id: nbqa-ruff

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
        - id: nbstripout
