name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install initial dependencies
      run: |
        python -m pip install -U pip
        pip install -e .[dev]

    - name: Run test
      run: pytest -v tests/ --cov=ipyoptimade

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11' && github.repository == 'aiidalab/ipyoptimade'
      uses: codecov/codecov-action@v3
      with:
        name: ipyoptimade
        flags: ipyoptimade-py-${{ matrix.python-version }}
